name: Build

on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    env:
      JAVA_OPTS: "-Xmx4G"
      SBT_OPTS: "-Dsbt.ci=true"
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Build Java Maven
        working-directory: java/maven
        run: ./mvnw --batch-mode -Dstyle.color=always --no-transfer-progress test-compile

      - name: Build Java Gradle
        working-directory: java/gradle
        run: ./gradlew gatlingClasses

      - name: Build Kotlin Maven
        working-directory: kotlin/maven
        run: ./mvnw --batch-mode -Dstyle.color=always --no-transfer-progress test-compile

      - name: Build Kotlin Gradle
        working-directory: kotlin/gradle
        run: ./gradlew gatlingClasses

      - name: Build Scala sbt
        working-directory: scala/sbt
        run: sbt Gatling/compile
